server.port=8081
spring.application.name=validateEmail
server.servlet.context-path=/validateEmail
# Replace with actual IMAP credentials
imap.host=imap.gmail.com
imap.username=noreplysfis007@gmail.com
imap.password=aycn wdzu lxyx gtxs
